# Generated by Django 3.2.25 on 2024-06-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
