# Generated by Django 3.2.25 on 2024-06-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_question_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
    ]
